import type { EnemyConfig, EnemyTypeName } from "../types";

export const ENEMY_CONFIGS: Record<EnemyTypeName, EnemyConfig> = {
  // ── Legacy TD enemies ──────────────────────────────────────────────────────
  zombie: {
    type: "zombie",
    name: "Zombie",
    maxHealth: 60,
    speed: 1.8,
    reward: 10,
    damage: 1,
    color: 0x3a7a3a,
    headColor: 0xc8b090,
    scale: 1.0,
    xpReward: 5,
    drops: [
      { itemId: "planks", chance: 0.4, count: 2 },
      { itemId: "apple",  chance: 0.2, count: 1 },
    ],
  },
  spider: {
    type: "spider",
    name: "Spider",
    maxHealth: 35,
    speed: 3.4,
    reward: 15,
    damage: 1,
    color: 0x1a1a1a,
    headColor: 0x1a1a1a,
    scale: 0.75,
    xpReward: 8,
    drops: [
      { itemId: "stick", chance: 0.5, count: 2 },
      { itemId: "flint", chance: 0.3, count: 1 },
    ],
  },
  golem: {
    type: "golem",
    name: "Stone Golem",
    maxHealth: 280,
    speed: 0.9,
    reward: 40,
    damage: 3,
    color: 0x888888,
    headColor: 0x666666,
    scale: 1.5,
    xpReward: 50,
    drops: [
      { itemId: "cobblestone", chance: 0.9, count: 8 },
      { itemId: "iron_ingot",  chance: 0.6, count: 3 },
    ],
  },

  // ── Helm's Deep enemies (flow-field AI) ───────────────────────────────────
  goblin: {
    type: "goblin",
    name: "Goblin",
    maxHealth: 40,
    speed: 3.8,
    reward: 8,
    damage: 1,
    color: 0x3a6a1a,
    headColor: 0x5a8a2a,
    scale: 0.75,
    xpReward: 5,
    drops: [
      { itemId: "arrow_item", chance: 0.4, count: 4 },
      { itemId: "flint",      chance: 0.3, count: 1 },
    ],
  },
  orc: {
    type: "orc",
    name: "Orc",
    maxHealth: 150,
    speed: 2.0,
    reward: 18,
    damage: 2,
    color: 0x7a4a1a,
    headColor: 0xaa6a30,
    scale: 1.1,
    xpReward: 15,
    drops: [
      { itemId: "iron_ingot", chance: 0.5, count: 2 },
      { itemId: "cobblestone",chance: 0.6, count: 4 },
    ],
  },
  troll: {
    type: "troll",
    name: "Troll",
    maxHealth: 400,
    speed: 0.9,
    reward: 45,
    damage: 4,
    color: 0x556644,
    headColor: 0x445533,
    scale: 1.6,
    xpReward: 40,
    drops: [
      { itemId: "iron_ingot", chance: 0.9, count: 4 },
      { itemId: "iron_block", chance: 0.3, count: 1 },
      { itemId: "apple",      chance: 0.5, count: 2 },
    ],
  },
  goblin_miner: {
    type: "goblin_miner",
    name: "Goblin Miner",
    maxHealth: 80,
    speed: 1.5,
    reward: 20,
    damage: 1,
    color: 0x886622,
    headColor: 0xaa8844,
    scale: 0.85,
    canBreakWalls: true,
    xpReward: 20,
    drops: [
      { itemId: "iron_ore",   chance: 0.6, count: 2 },
      { itemId: "coal_ore",   chance: 0.7, count: 2 },
      { itemId: "stick",      chance: 0.5, count: 4 },
    ],
  },
  skeleton: {
    type: "skeleton",
    name: "Skeleton",
    maxHealth: 30,
    speed: 2.0,
    reward: 15,
    damage: 2,   // arrow damage
    color: 0xdddddd,
    headColor: 0xeeeeee,
    scale: 0.95,
    xpReward: 10,
    drops: [
      { itemId: "arrow_item", chance: 0.6, count: 4 },
      { itemId: "flint",      chance: 0.3, count: 1 },
    ],
  },
  creeper: {
    type: "creeper",
    name: "Creeper",
    maxHealth: 40,
    speed: 2.5,
    reward: 20,
    damage: 6,   // explosion damage (applied in Game.ts)
    color: 0x1a7a1a,
    headColor: 0x1a7a1a,
    scale: 0.9,
    xpReward: 10,
    drops: [
      { itemId: "gunpowder", chance: 0.8, count: 2 },
      { itemId: "flint",     chance: 0.3, count: 1 },
    ],
  },
};
